/**
 * Comprehensive Agent Registry defining 80+ specialized AI Agents.
 * Every agent has a single responsibility, exposes APIs, and communicates through the EventBus.
 */

export const AGENT_DOMAINS = [
  { id: "orchestration", name: "Orchestration & Core", icon: "🤖" },
  { id: "analysis", name: "Code & Architecture Analysis", icon: "🔍" },
  { id: "testing_cicd", name: "Testing & Deployment", icon: "🚀" },
  { id: "portfolio_resume", name: "Portfolio & Career Sync", icon: "📄" },
  { id: "content_seo", name: "SEO & Content Generation", icon: "📰" },
  { id: "graphics_diagrams", name: "Graphics & Diagrams", icon: "🎨" },
  { id: "media_presentation", name: "Media & Presentations", icon: "🎬" },
  { id: "analytics_telemetry", name: "Analytics & GitHub Telemetry", icon: "📊" },
  { id: "interaction_advisory", name: "Interaction & Advisory", icon: "💬" },
  { id: "evaluation_ranking", name: "Intelligence & Ranking", icon: "🏆" },
  { id: "system_infrastructure", name: "System & Infrastructure", icon: "⚙️" },
  { id: "ai_ui_customization", name: "AI Engine & Customization", icon: "🎨" },
];

export const ALL_AGENTS = [
  // 1. Orchestration & Core
  {
    id: "master-orchestrator",
    name: "Master Orchestrator Agent",
    domain: "orchestration",
    icon: "🧠",
    description: "Coordinates workflow execution across all 80+ specialized agents.",
    listensTo: ["system.start", "github.push", "workflow.trigger"],
    emits: ["orchestration.dispatch", "pipeline.complete"],
  },
  {
    id: "github-monitor",
    name: "GitHub Monitor Agent",
    domain: "orchestration",
    icon: "📡",
    description: "Monitors GitHub webhooks and push events in real-time.",
    listensTo: ["system.start", "github.push"],
    emits: ["repo.detected"],
  },

  // 2. Code & Architecture Analysis
  {
    id: "repo-scanner",
    name: "Repository Scanner Agent",
    domain: "analysis",
    icon: "🔍",
    description: "Scans repository directories and constructs file tree topologies.",
    listensTo: ["repo.detected"],
    emits: ["repo.scanned"],
  },
  {
    id: "repo-analysis",
    name: "Repository Analysis Agent",
    domain: "analysis",
    icon: "📊",
    description: "Analyzes code lines, complexity scores, and language distributions.",
    listensTo: ["repo.scanned"],
    emits: ["repo.analyzed"],
  },
  {
    id: "readme-analysis",
    name: "README Analysis Agent",
    domain: "analysis",
    icon: "📖",
    description: "Parses README files to extract setup instructions and project goals.",
    listensTo: ["repo.scanned"],
    emits: ["readme.parsed"],
  },
  {
    id: "documentation",
    name: "Documentation Agent",
    domain: "analysis",
    icon: "📝",
    description: "Generates comprehensive API documentation and Markdown specs.",
    listensTo: ["repo.analyzed"],
    emits: ["docs.generated"],
  },
  {
    id: "project-summary",
    name: "Project Summary Agent",
    domain: "analysis",
    icon: "💡",
    description: "Synthesizes high-level executive project summaries.",
    listensTo: ["repo.analyzed"],
    emits: ["summary.created"],
  },
  {
    id: "technology-detection",
    name: "Technology Detection Agent",
    domain: "analysis",
    icon: "⚡",
    description: "Identifies frameworks, libraries, runtime environments, and databases.",
    listensTo: ["repo.scanned"],
    emits: ["tech.detected"],
  },
  {
    id: "dependency-analysis",
    name: "Dependency Analysis Agent",
    domain: "analysis",
    icon: "📦",
    description: "Evaluates package.json/requirements.txt for dependency health.",
    listensTo: ["repo.scanned"],
    emits: ["dependencies.analyzed"],
  },
  {
    id: "folder-structure",
    name: "Folder Structure Agent",
    domain: "analysis",
    icon: "📁",
    description: "Maps architectural directory layouts and component modularity.",
    listensTo: ["repo.scanned"],
    emits: ["structure.mapped"],
  },
  {
    id: "architecture-analysis",
    name: "Architecture Analysis Agent",
    domain: "analysis",
    icon: "🏗️",
    description: "Detects microservice, monorepo, serverless, or MVC design patterns.",
    listensTo: ["repo.analyzed"],
    emits: ["architecture.analyzed"],
  },
  {
    id: "database-analysis",
    name: "Database Analysis Agent",
    domain: "analysis",
    icon: "🛢️",
    description: "Inspects ORMs, SQL schemas, migrations, and NoSQL collections.",
    listensTo: ["repo.scanned"],
    emits: ["database.analyzed"],
  },
  {
    id: "api-analysis",
    name: "API Analysis Agent",
    domain: "analysis",
    icon: "🔌",
    description: "Scans REST endpoints, GraphQL schemas, and gRPC definitions.",
    listensTo: ["repo.scanned"],
    emits: ["api.analyzed"],
  },
  {
    id: "backend-analysis",
    name: "Backend Analysis Agent",
    domain: "analysis",
    icon: "⚙️",
    description: "Evaluates backend controllers, middleware, and authentication.",
    listensTo: ["repo.scanned"],
    emits: ["backend.analyzed"],
  },
  {
    id: "frontend-analysis",
    name: "Frontend Analysis Agent",
    domain: "analysis",
    icon: "💻",
    description: "Analyzes React components, state management, and CSS design tokens.",
    listensTo: ["repo.scanned"],
    emits: ["frontend.analyzed"],
  },
  {
    id: "security-analysis",
    name: "Security Analysis Agent",
    domain: "analysis",
    icon: "🛡️",
    description: "Scans for secret leakage, vulnerable dependencies, and OWASP risks.",
    listensTo: ["repo.scanned"],
    emits: ["security.audited"],
  },
  {
    id: "performance-analysis",
    name: "Performance Analysis Agent",
    domain: "analysis",
    icon: "⚡",
    description: "Evaluates bundle size, lazy loading, rendering bottlenecks, and latency.",
    listensTo: ["repo.analyzed"],
    emits: ["performance.evaluated"],
  },
  {
    id: "code-quality",
    name: "Code Quality Agent",
    domain: "analysis",
    icon: "✨",
    description: "Calculates maintainability index, cyclomatic complexity, and duplication.",
    listensTo: ["repo.analyzed"],
    emits: ["quality.scored"],
  },
  {
    id: "code-review",
    name: "Code Review Agent",
    domain: "analysis",
    icon: "👀",
    description: "Generates automated code review comments for pull requests.",
    listensTo: ["repo.analyzed"],
    emits: ["review.published"],
  },
  {
    id: "bug-detection",
    name: "Bug Detection Agent",
    domain: "analysis",
    icon: "🐛",
    description: "Uses static analysis to identify potential null pointer and memory leaks.",
    listensTo: ["repo.analyzed"],
    emits: ["bugs.flagged"],
  },

  // 3. Testing & CI/CD
  {
    id: "testing",
    name: "Testing Agent",
    domain: "testing_cicd",
    icon: "🧪",
    description: "Evaluates overall test suite coverage and test runner configurations.",
    listensTo: ["repo.analyzed"],
    emits: ["testing.evaluated"],
  },
  {
    id: "unit-test",
    name: "Unit Test Agent",
    domain: "testing_cicd",
    icon: "🎯",
    description: "Generates automated unit tests for untested helper functions.",
    listensTo: ["testing.evaluated"],
    emits: ["unittests.generated"],
  },
  {
    id: "integration-test",
    name: "Integration Test Agent",
    domain: "testing_cicd",
    icon: "🔗",
    description: "Drafts end-to-end integration workflows using Playwright/Cypress.",
    listensTo: ["testing.evaluated"],
    emits: ["e2etests.generated"],
  },
  {
    id: "deployment",
    name: "Deployment Agent",
    domain: "testing_cicd",
    icon: "🚀",
    description: "Orchestrates multi-stage build deployments to edge networks.",
    listensTo: ["pipeline.complete"],
    emits: ["deployment.triggered"],
  },
  {
    id: "cicd",
    name: "CI/CD Agent",
    domain: "testing_cicd",
    icon: "🔄",
    description: "Generates GitHub Actions workflow YAML configurations.",
    listensTo: ["repo.scanned"],
    emits: ["cicd.configured"],
  },
  {
    id: "docker",
    name: "Docker Agent",
    domain: "testing_cicd",
    icon: "🐳",
    description: "Designs multi-stage Dockerfiles and Docker Compose files.",
    listensTo: ["repo.scanned"],
    emits: ["docker.generated"],
  },
  {
    id: "cloud-deployment",
    name: "Cloud Deployment Agent",
    domain: "testing_cicd",
    icon: "☁️",
    description: "Manages AWS/Vercel/GCP infrastructure scripts and terraform templates.",
    listensTo: ["deployment.triggered"],
    emits: ["cloud.deployed"],
  },

  // 4. Portfolio & Profile Sync
  {
    id: "portfolio-update",
    name: "Portfolio Update Agent",
    domain: "portfolio_resume",
    icon: "🌐",
    description: "Injects new projects directly into the live portfolio showcase grid.",
    listensTo: ["docs.generated"],
    emits: ["portfolio.updated"],
  },
  {
    id: "profile-update",
    name: "Profile Update Agent",
    domain: "portfolio_resume",
    icon: "👤",
    description: "Updates developer profile bio and headline badges.",
    listensTo: ["portfolio.updated"],
    emits: ["profile.updated"],
  },
  {
    id: "resume-update",
    name: "Resume Update Agent",
    domain: "portfolio_resume",
    icon: "📄",
    description: "Auto-generates resume accomplishment bullet points based on new repos.",
    listensTo: ["repo.analyzed"],
    emits: ["resume.updated"],
  },
  {
    id: "cv-update",
    name: "CV Update Agent",
    domain: "portfolio_resume",
    icon: "📑",
    description: "Formats academic and research CV entries.",
    listensTo: ["resume.updated"],
    emits: ["cv.updated"],
  },
  {
    id: "skill-update",
    name: "Skill Update Agent",
    domain: "portfolio_resume",
    icon: "⭐",
    description: "Calculates updated skill level ratings from code commit frequency.",
    listensTo: ["tech.detected"],
    emits: ["skills.updated"],
  },
  {
    id: "experience-update",
    name: "Experience Update Agent",
    domain: "portfolio_resume",
    icon: "💼",
    description: "Logs project engineering milestones under career experience.",
    listensTo: ["portfolio.updated"],
    emits: ["experience.updated"],
  },
  {
    id: "timeline-update",
    name: "Timeline Update Agent",
    domain: "portfolio_resume",
    icon: "⏳",
    description: "Appends repository release milestones to the career timeline.",
    listensTo: ["portfolio.updated"],
    emits: ["timeline.updated"],
  },
  {
    id: "achievement-update",
    name: "Achievement Update Agent",
    domain: "portfolio_resume",
    icon: "🏆",
    description: "Flags major project milestones (e.g. 100+ stars, zero vulnerabilities).",
    listensTo: ["quality.scored"],
    emits: ["achievement.unlocked"],
  },
  {
    id: "certificate-update",
    name: "Certificate Update Agent",
    domain: "portfolio_resume",
    icon: "📜",
    description: "Indexes verified technical certificates and credentials.",
    listensTo: ["achievement.unlocked"],
    emits: ["certificate.indexed"],
  },
  {
    id: "project-recommendation",
    name: "Project Recommendation Agent",
    domain: "portfolio_resume",
    icon: "💡",
    description: "Recommends next open-source projects based on skill growth gaps.",
    listensTo: ["skills.updated"],
    emits: ["recommendations.generated"],
  },
  {
    id: "freelance-recommendation",
    name: "Freelance Recommendation Agent",
    domain: "portfolio_resume",
    icon: "💰",
    description: "Identifies matching freelance client opportunities for tech stack.",
    listensTo: ["skills.updated"],
    emits: ["freelance.suggested"],
  },

  // 5. SEO & Content Generation
  {
    id: "seo",
    name: "SEO Agent",
    domain: "content_seo",
    icon: "🚀",
    description: "Optimizes portfolio page headers and schema markup for search engines.",
    listensTo: ["portfolio.updated"],
    emits: ["seo.optimized"],
  },
  {
    id: "keyword",
    name: "Keyword Agent",
    domain: "content_seo",
    icon: "🔑",
    description: "Extracts high-ranking technical keywords from repository code.",
    listensTo: ["tech.detected"],
    emits: ["keywords.extracted"],
  },
  {
    id: "metadata",
    name: "Metadata Agent",
    domain: "content_seo",
    icon: "🏷️",
    description: "Generates OpenGraph and Twitter card meta tags for project sharing.",
    listensTo: ["seo.optimized"],
    emits: ["metadata.generated"],
  },
  {
    id: "blog-writing",
    name: "Blog Writing Agent",
    domain: "content_seo",
    icon: "✍️",
    description: "Drafts comprehensive technical blog articles explaining project design.",
    listensTo: ["docs.generated"],
    emits: ["blog.published"],
  },
  {
    id: "technical-article",
    name: "Technical Article Agent",
    domain: "content_seo",
    icon: "📰",
    description: "Writes deep-dive architectural whitepapers and tutorials.",
    listensTo: ["architecture.analyzed"],
    emits: ["article.published"],
  },
  {
    id: "linkedin-post",
    name: "LinkedIn Post Agent",
    domain: "content_seo",
    icon: "💼",
    description: "Formulates professional LinkedIn announcements with hashtags.",
    listensTo: ["blog.published"],
    emits: ["linkedin.drafted"],
  },
  {
    id: "facebook-post",
    name: "Facebook Post Agent",
    domain: "content_seo",
    icon: "📘",
    description: "Creates casual developer community updates.",
    listensTo: ["blog.published"],
    emits: ["facebook.drafted"],
  },
  {
    id: "twitter-post",
    name: "Twitter/X Post Agent",
    domain: "content_seo",
    icon: "🐦",
    description: "Crafts concise Twitter/X release threads with code snippets.",
    listensTo: ["blog.published"],
    emits: ["twitter.drafted"],
  },
  {
    id: "medium-article",
    name: "Medium Article Agent",
    domain: "content_seo",
    icon: "✍️",
    description: "Formats and submits blog content to Medium tech publications.",
    listensTo: ["blog.published"],
    emits: ["medium.published"],
  },
  {
    id: "release-notes",
    name: "Release Notes Agent",
    domain: "content_seo",
    icon: "📋",
    description: "Summarizes version release changes for software updates.",
    listensTo: ["repo.analyzed"],
    emits: ["releasenotes.created"],
  },
  {
    id: "changelog",
    name: "Changelog Agent",
    domain: "content_seo",
    icon: "📜",
    description: "Maintains standard CHANGELOG.md files based on Git commits.",
    listensTo: ["repo.analyzed"],
    emits: ["changelog.updated"],
  },

  // 6. Graphics & Diagrams
  {
    id: "project-cover",
    name: "Project Cover Agent",
    domain: "graphics_diagrams",
    icon: "🎨",
    description: "Automatically designs professional project cover art and banners.",
    listensTo: ["tech.detected"],
    emits: ["cover.rendered"],
  },
  {
    id: "project-thumbnail",
    name: "Project Thumbnail Agent",
    domain: "graphics_diagrams",
    icon: "🖼️",
    description: "Generates square preview thumbnails for project grids.",
    listensTo: ["cover.rendered"],
    emits: ["thumbnail.rendered"],
  },
  {
    id: "image-generation",
    name: "Image Generation Agent",
    domain: "graphics_diagrams",
    icon: "✨",
    description: "Renders custom AI visual illustrations for documentation.",
    listensTo: ["cover.rendered"],
    emits: ["image.generated"],
  },
  {
    id: "architecture-diagram",
    name: "Architecture Diagram Agent",
    domain: "graphics_diagrams",
    icon: "📐",
    description: "Renders Mermaid.js systems architecture component diagrams.",
    listensTo: ["architecture.analyzed"],
    emits: ["archdiagram.rendered"],
  },
  {
    id: "flowchart",
    name: "Flowchart Agent",
    domain: "graphics_diagrams",
    icon: "🔀",
    description: "Generates execution flowcharts for complex algorithms.",
    listensTo: ["repo.analyzed"],
    emits: ["flowchart.rendered"],
  },
  {
    id: "er-diagram",
    name: "ER Diagram Agent",
    domain: "graphics_diagrams",
    icon: "🗄️",
    description: "Builds entity-relationship database schema diagrams.",
    listensTo: ["database.analyzed"],
    emits: ["erdiagram.rendered"],
  },
  {
    id: "uml-diagram",
    name: "UML Diagram Agent",
    domain: "graphics_diagrams",
    icon: "🧩",
    description: "Generates class inheritance and sequence diagrams.",
    listensTo: ["folder-structure"],
    emits: ["umldiagram.rendered"],
  },

  // 7. Media & Presentation
  {
    id: "video-script",
    name: "Video Script Agent",
    domain: "media_presentation",
    icon: "🎬",
    description: "Drafts YouTube / Loom product demo video scripts.",
    listensTo: ["summary.created"],
    emits: ["videoscript.drafted"],
  },
  {
    id: "demo-script",
    name: "Demo Script Agent",
    domain: "media_presentation",
    icon: "🎙️",
    description: "Creates live presentation walkthrough scripts.",
    listensTo: ["summary.created"],
    emits: ["demoscript.drafted"],
  },
  {
    id: "presentation",
    name: "Presentation Agent",
    domain: "media_presentation",
    icon: "📊",
    description: "Generates HTML slide decks for technical talks.",
    listensTo: ["summary.created"],
    emits: ["slides.generated"],
  },
  {
    id: "powerpoint",
    name: "PowerPoint Agent",
    domain: "media_presentation",
    icon: "💻",
    description: "Exports slide presentations to PPTX format.",
    listensTo: ["slides.generated"],
    emits: ["pptx.exported"],
  },

  // 8. Analytics & GitHub Telemetry
  {
    id: "analytics",
    name: "Analytics Agent",
    domain: "analytics_telemetry",
    icon: "📈",
    description: "Aggregates site metrics and multi-agent workflow throughput.",
    listensTo: ["system.start", "pipeline.complete"],
    emits: ["analytics.updated"],
  },
  {
    id: "visitor-analytics",
    name: "Visitor Analytics Agent",
    domain: "analytics_telemetry",
    icon: "👥",
    description: "Tracks geographic visitor traffic and page engagement.",
    listensTo: ["analytics.updated"],
    emits: ["visitors.tracked"],
  },
  {
    id: "github-stats",
    name: "GitHub Stats Agent",
    domain: "analytics_telemetry",
    icon: "🐙",
    description: "Fetches live repository commit and pull request statistics.",
    listensTo: ["repo.detected"],
    emits: ["ghstats.fetched"],
  },
  {
    id: "github-contribution",
    name: "GitHub Contribution Agent",
    domain: "analytics_telemetry",
    icon: "🟩",
    description: "Renders contribution heatmaps and commit velocity metrics.",
    listensTo: ["ghstats.fetched"],
    emits: ["contributions.rendered"],
  },
  {
    id: "github-stars",
    name: "GitHub Stars Agent",
    domain: "analytics_telemetry",
    icon: "⭐",
    description: "Tracks stargazers growth trends across all public repositories.",
    listensTo: ["ghstats.fetched"],
    emits: ["stars.tracked"],
  },
  {
    id: "github-followers",
    name: "GitHub Followers Agent",
    domain: "analytics_telemetry",
    icon: "🫂",
    description: "Monitors follower growth and network connections.",
    listensTo: ["ghstats.fetched"],
    emits: ["followers.tracked"],
  },

  // 9. Interaction & Assistance
  {
    id: "contact",
    name: "Contact Agent",
    domain: "interaction_advisory",
    icon: "📩",
    description: "Processes user inquiries and routes incoming messages.",
    listensTo: ["contact.submitted"],
    emits: ["message.routed"],
  },
  {
    id: "email",
    name: "Email Agent",
    domain: "interaction_advisory",
    icon: "✉️",
    description: "Sends automated confirmation and client notification emails.",
    listensTo: ["message.routed"],
    emits: ["email.sent"],
  },
  {
    id: "notification",
    name: "Notification Agent",
    domain: "interaction_advisory",
    icon: "🔔",
    description: "Triggers browser notifications for agent state updates.",
    listensTo: ["email.sent", "pipeline.complete"],
    emits: ["notification.pushed"],
  },
  {
    id: "ai-chatbot",
    name: "AI Chatbot Agent",
    domain: "interaction_advisory",
    icon: "🤖",
    description: "Answers visitor questions about projects and experience live.",
    listensTo: ["chat.received"],
    emits: ["chat.replied"],
  },
  {
    id: "recommendation",
    name: "Recommendation Agent",
    domain: "interaction_advisory",
    icon: "✨",
    description: "Suggests relevant projects to visitors based on browsing history.",
    listensTo: ["visitors.tracked"],
    emits: ["content.recommended"],
  },
  {
    id: "learning-roadmap",
    name: "Learning Roadmap Agent",
    domain: "interaction_advisory",
    icon: "🗺️",
    description: "Generates custom skill acquisition roadmaps.",
    listensTo: ["skills.updated"],
    emits: ["roadmap.created"],
  },
  {
    id: "career-advisor",
    name: "Career Advisor Agent",
    domain: "interaction_advisory",
    icon: "🎓",
    description: "Provides strategic career growth insights.",
    listensTo: ["resume.updated"],
    emits: ["career.advised"],
  },
  {
    id: "freelance-advisor",
    name: "Freelance Advisor Agent",
    domain: "interaction_advisory",
    icon: "💼",
    description: "Estimates project rates and freelance contract proposals.",
    listensTo: ["freelance.suggested"],
    emits: ["proposal.drafted"],
  },
  {
    id: "interview-prep",
    name: "Interview Preparation Agent",
    domain: "interaction_advisory",
    icon: "🎙️",
    description: "Generates practice system design questions from repository code.",
    listensTo: ["architecture.analyzed"],
    emits: ["interview.prepared"],
  },

  // 10. Intelligence & Ranking
  {
    id: "project-difficulty",
    name: "Project Difficulty Analyzer",
    domain: "evaluation_ranking",
    icon: "⚡",
    description: "Rates codebase complexity score from Beginner to Elite Master.",
    listensTo: ["quality.scored"],
    emits: ["difficulty.scored"],
  },
  {
    id: "project-ranking",
    name: "Project Ranking Agent",
    domain: "evaluation_ranking",
    icon: "🏅",
    description: "Ranks top portfolio projects based on impact and stars.",
    listensTo: ["difficulty.scored"],
    emits: ["projects.ranked"],
  },
  {
    id: "trending-tech",
    name: "Trending Technology Agent",
    domain: "evaluation_ranking",
    icon: "🔥",
    description: "Scans tech industry trends to suggest modern library upgrades.",
    listensTo: ["tech.detected"],
    emits: ["trends.analyzed"],
  },

  // 11. System & Infrastructure
  {
    id: "version-management",
    name: "Version Management Agent",
    domain: "system_infrastructure",
    icon: "🏷️",
    description: "Manages semantic versioning (SemVer) and git tags.",
    listensTo: ["releasenotes.created"],
    emits: ["version.bumped"],
  },
  {
    id: "backup",
    name: "Backup Agent",
    domain: "system_infrastructure",
    icon: "💾",
    description: "Performs automated state backups to localStorage and JSON artifacts.",
    listensTo: ["portfolio.updated"],
    emits: ["backup.completed"],
  },
  {
    id: "database-sync",
    name: "Database Sync Agent",
    domain: "system_infrastructure",
    icon: "🔄",
    description: "Synchronizes local state memory with remote database stores.",
    listensTo: ["backup.completed"],
    emits: ["dbsync.done"],
  },
  {
    id: "cloud-sync",
    name: "Cloud Sync Agent",
    domain: "system_infrastructure",
    icon: "☁️",
    description: "Syncs portfolio state across distributed cloud storage nodes.",
    listensTo: ["backup.completed"],
    emits: ["cloudsync.done"],
  },
  {
    id: "cache-management",
    name: "Cache Management Agent",
    domain: "system_infrastructure",
    icon: "⚡",
    description: "Invalidates and refreshes stale API data caches.",
    listensTo: ["system.start"],
    emits: ["cache.cleared"],
  },
  {
    id: "search",
    name: "Search Agent",
    domain: "system_infrastructure",
    icon: "🔎",
    description: "Indexes project text for global search operations.",
    listensTo: ["portfolio.updated"],
    emits: ["search.indexed"],
  },
  {
    id: "portfolio-search",
    name: "Portfolio Search Agent",
    domain: "system_infrastructure",
    icon: "🔍",
    description: "Powers instant multi-filter search queries across portfolio items.",
    listensTo: ["search.indexed"],
    emits: ["query.executed"],
  },
  {
    id: "voice-assistant",
    name: "Voice Assistant Agent",
    domain: "system_infrastructure",
    icon: "🎙️",
    description: "Processes voice speech commands for portfolio navigation.",
    listensTo: ["voice.input"],
    emits: ["voice.executed"],
  },
  {
    id: "accessibility",
    name: "Accessibility Agent",
    domain: "system_infrastructure",
    icon: "♿",
    description: "Audits WCAG AA compliance, ARIA attributes, and screen reader labels.",
    listensTo: ["portfolio.updated"],
    emits: ["a11y.audited"],
  },
  {
    id: "localization",
    name: "Localization Agent",
    domain: "system_infrastructure",
    icon: "🌐",
    description: "Manages locale formats for dates, currencies, and numbers.",
    listensTo: ["system.start"],
    emits: ["locale.set"],
  },
  {
    id: "translation",
    name: "Translation Agent",
    domain: "system_infrastructure",
    icon: "🗣️",
    description: "Translates blog articles and summaries into multiple languages.",
    listensTo: ["blog.published"],
    emits: ["translation.done"],
  },
  {
    id: "auto-fix",
    name: "Auto Fix Agent",
    domain: "system_infrastructure",
    icon: "🛠️",
    description: "Applies automated patch fixes for lint and formatting errors.",
    listensTo: ["bugs.flagged"],
    emits: ["autofix.applied"],
  },
  {
    id: "error-recovery",
    name: "Error Recovery Agent",
    domain: "system_infrastructure",
    icon: "🏥",
    description: "Catches uncaught exceptions and restores state to last stable checkpoint.",
    listensTo: ["system.error"],
    emits: ["recovery.complete"],
  },
  {
    id: "health-monitoring",
    name: "Health Monitoring Agent",
    domain: "system_infrastructure",
    icon: "💓",
    description: "Monitors agent heartbeat health and memory consumption.",
    listensTo: ["system.start"],
    emits: ["health.reported"],
  },
  {
    id: "logging",
    name: "Logging Agent",
    domain: "system_infrastructure",
    icon: "📜",
    description: "Persists telemetry logs with timestamping.",
    listensTo: ["*"],
    emits: ["log.written"],
  },
  {
    id: "monitoring",
    name: "Monitoring Agent",
    domain: "system_infrastructure",
    icon: "🖥️",
    description: "Monitors system resources and browser memory.",
    listensTo: ["system.start"],
    emits: ["metrics.collected"],
  },
  {
    id: "scheduler",
    name: "Scheduler Agent",
    domain: "system_infrastructure",
    icon: "⏰",
    description: "Schedules recurring cron tasks for periodic repo re-indexing.",
    listensTo: ["system.start"],
    emits: ["cron.fired"],
  },
  {
    id: "workflow-automation",
    name: "Workflow Automation Agent",
    domain: "system_infrastructure",
    icon: "⚡",
    description: "Executes custom multi-step event automation recipes.",
    listensTo: ["workflow.trigger"],
    emits: ["workflow.completed"],
  },
  {
    id: "memory",
    name: "Memory Agent",
    domain: "system_infrastructure",
    icon: "💾",
    description: "Manages short-term and long-term agent memory context.",
    listensTo: ["system.start"],
    emits: ["memory.synced"],
  },

  // 12. AI Engine & Customization
  {
    id: "knowledge-base",
    name: "Knowledge Base Agent",
    domain: "ai_ui_customization",
    icon: "📚",
    description: "Indexes code documentation into a structured knowledge graph.",
    listensTo: ["docs.generated"],
    emits: ["kb.indexed"],
  },
  {
    id: "rag",
    name: "RAG Agent",
    domain: "ai_ui_customization",
    icon: "🔎",
    description: "Retrieves context chunks for LLM query synthesis.",
    listensTo: ["chat.received"],
    emits: ["rag.retrieved"],
  },
  {
    id: "llm-routing",
    name: "LLM Routing Agent",
    domain: "ai_ui_customization",
    icon: "🔀",
    description: "Dynamically routes prompts to optimal model providers (Gemini, Claude, GPT).",
    listensTo: ["prompt.optimized"],
    emits: ["llm.routed"],
  },
  {
    id: "prompt-optimization",
    name: "Prompt Optimization Agent",
    domain: "ai_ui_customization",
    icon: "✍️",
    description: "Refines user prompts with meta-prompting techniques.",
    listensTo: ["chat.received"],
    emits: ["prompt.optimized"],
  },
  {
    id: "model-selection",
    name: "Model Selection Agent",
    domain: "ai_ui_customization",
    icon: "🤖",
    description: "Selects best LLM size based on task complexity.",
    listensTo: ["llm.routed"],
    emits: ["model.selected"],
  },
  {
    id: "cost-optimization",
    name: "Cost Optimization Agent",
    domain: "ai_ui_customization",
    icon: "💵",
    description: "Monitors LLM token usage to minimize API costs.",
    listensTo: ["llm.routed"],
    emits: ["cost.calculated"],
  },
  {
    id: "offline-sync",
    name: "Offline Sync Agent",
    domain: "ai_ui_customization",
    icon: "📶",
    description: "Queues events when offline and syncs upon reconnection.",
    listensTo: ["system.start"],
    emits: ["offline.queued"],
  },
  {
    id: "settings",
    name: "Settings Agent",
    domain: "ai_ui_customization",
    icon: "⚙️",
    description: "Manages user configuration preferences.",
    listensTo: ["settings.update"],
    emits: ["settings.saved"],
  },
  {
    id: "theme",
    name: "Theme Agent",
    domain: "ai_ui_customization",
    icon: "🎨",
    description: "Controls 12 preset profile theme transitions and CSS variables.",
    listensTo: ["theme.change"],
    emits: ["theme.applied"],
  },
  {
    id: "animation",
    name: "Animation Agent",
    domain: "ai_ui_customization",
    icon: "✨",
    description: "Manages Framer Motion transition curves and keyframes.",
    listensTo: ["system.start"],
    emits: ["animations.ready"],
  },
  {
    id: "3d-rendering",
    name: "3D Rendering Agent",
    domain: "ai_ui_customization",
    icon: "🔮",
    description: "Renders Three.js WebGL canvas objects and volumetric shader lights.",
    listensTo: ["system.start"],
    emits: ["3d.rendered"],
  },
  {
    id: "dashboard",
    name: "Dashboard Agent",
    domain: "ai_ui_customization",
    icon: "🎛️",
    description: "Controls Swarm Control Center layouts.",
    listensTo: ["system.start"],
    emits: ["dashboard.rendered"],
  },
  {
    id: "widget",
    name: "Widget Agent",
    domain: "ai_ui_customization",
    icon: "🧩",
    description: "Manages dynamic widget embedding.",
    listensTo: ["system.start"],
    emits: ["widget.mounted"],
  },
];
