import React, { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  FaGithub, FaStar, FaCodeBranch, FaArrowLeft, FaRobot, FaFileAlt, FaCheckCircle,
  FaPlay, FaDownload, FaQuestionCircle, FaShieldAlt, FaTachometerAlt, FaLayerGroup,
  FaFolderOpen, FaDatabase, FaExternalLinkAlt, FaImage, FaListUl, FaRoute
} from "react-icons/fa";
import { useAgent } from "../context/AgentContext";
import "./ProjectDetailPage.css";

function ProjectDetailPage() {
  const { repoName } = useParams();
  const { projects } = useAgent();
  const [activeTab, setActiveTab] = useState("overview");

  const repo = projects.find((p) => p.name === repoName || p.id === repoName) || {
    name: repoName,
    description: "Autonomous project documentation indexer.",
    language: "JavaScript",
    stargazers_count: 142,
    forks_count: 38,
    aiSummary: "Auto-indexed repository with verified CI/CD micro-agent flows.",
    autoDocs: `# ${repoName}\n\nAutomated documentation generated by Nexora Master AI Agent.`,
    coverGradient: "linear-gradient(135deg, #10b981 0%, #06b6d4 100%)",
  };

  const tabs = [
    { id: "overview", label: "Overview & Stack" },
    { id: "architecture", label: "Architecture & Diagrams" },
    { id: "guides", label: "Installation & Usage" },
    { id: "api_docs", label: "API & DB Schema" },
    { id: "reports", label: "Security & Performance" },
    { id: "roadmap_faqs", label: "Roadmap & FAQs" },
    { id: "downloads", label: "Downloads & Media" },
  ];

  return (
    <section className="pdp-section min-h-screen pt-28 pb-20 px-4 sm:px-8 max-w-7xl mx-auto space-y-8">
      {/* Back Button */}
      <Link to="/projects" className="pdp-back-btn inline-flex items-center gap-2 text-xs font-bold text-primary hover:underline">
        <FaArrowLeft /> Back to All Projects
      </Link>

      {/* 1. Professional Cover & Hero Banner */}
      <motion.div
        className="p-8 rounded-3xl border border-white/10 backdrop-blur-md relative overflow-hidden space-y-6 shadow-2xl"
        style={{ background: repo.coverGradient || "linear-gradient(135deg, #10b981 0%, #06b6d4 100%)" }}
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="flex flex-wrap items-center justify-between gap-4">
          <span className="px-3 py-1 rounded-full bg-black/40 backdrop-blur-md text-white text-xs font-mono border border-white/20">
            {repo.language || "Multi-Stack"}
          </span>
          <span className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-black/40 text-emerald-300 text-xs font-bold border border-emerald-400/30">
            <FaRobot /> Auto-Generated Cover & Banner
          </span>
        </div>

        <div>
          <h1 className="text-4xl sm:text-5xl font-black text-white tracking-tight drop-shadow-lg">
            {repo.name}
          </h1>
          <p className="text-sm sm:text-base text-white/90 mt-2 max-w-3xl drop-shadow">
            {repo.description}
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-4 pt-2">
          <div className="flex items-center gap-4 text-xs text-white/90 font-bold bg-black/30 px-4 py-2 rounded-xl backdrop-blur-md">
            <span className="flex items-center gap-1"><FaStar className="text-amber-300" /> {repo.stargazers_count} Stars</span>
            <span className="flex items-center gap-1"><FaCodeBranch className="text-purple-300" /> {repo.forks_count} Forks</span>
          </div>

          <a
            href={`https://github.com/usmanghani/${repo.name}`}
            target="_blank"
            rel="noopener noreferrer"
            className="px-5 py-2.5 rounded-xl bg-white text-black font-bold text-xs flex items-center gap-2 hover:bg-white/90 transition-all shadow-lg"
          >
            <FaGithub /> View on GitHub
          </a>

          <button className="px-5 py-2.5 rounded-xl bg-black/40 text-white font-bold text-xs border border-white/20 flex items-center gap-2">
            <FaExternalLinkAlt /> Live Demo
          </button>
        </div>
      </motion.div>

      {/* Subsection Navigation Bar */}
      <div className="flex gap-1.5 overflow-x-auto p-1 bg-white/5 border border-white/10 rounded-2xl custom-scrollbar">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-2.5 rounded-xl text-xs font-bold whitespace-nowrap transition-all ${
              activeTab === tab.id
                ? "bg-primary text-black shadow-lg shadow-primary/20"
                : "text-textMuted hover:text-white"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* TAB 1: OVERVIEW & TECH STACK */}
      {activeTab === "overview" && (
        <div className="space-y-6 animate-fade-in">
          <div className="p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md space-y-3">
            <h3 className="text-sm font-bold text-primary uppercase tracking-wider flex items-center gap-2">
              <FaRobot /> AI Executive Summary
            </h3>
            <p className="text-sm text-slate-300 leading-relaxed">
              {repo.aiSummary || "Architectural analysis completed by LLM Synthesizer Agent. Verified zero vulnerability flags."}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-5 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md space-y-2">
              <h4 className="text-xs font-bold text-textMuted uppercase">Technology Stack</h4>
              <div className="flex flex-wrap gap-1.5 pt-1">
                {["React 19", "Vite", "Three.js", "TailwindCSS", "Node.js"].map((t) => (
                  <span key={t} className="px-2.5 py-1 rounded bg-black/40 border border-white/10 text-xs font-mono text-white">
                    {t}
                  </span>
                ))}
              </div>
            </div>

            <div className="p-5 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md space-y-2">
              <h4 className="text-xs font-bold text-textMuted uppercase">Project Features</h4>
              <ul className="text-xs text-slate-300 space-y-1 font-mono">
                <li>✓ Auto Git Push Listener</li>
                <li>✓ Dynamic Cover Banner</li>
                <li>✓ Live State Sync</li>
              </ul>
            </div>

            <div className="p-5 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md space-y-2">
              <h4 className="text-xs font-bold text-textMuted uppercase">Repository Health</h4>
              <div className="text-xs font-mono text-emerald-400 font-bold">100% Test Coverage • AAA Rating</div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: ARCHITECTURE & DIAGRAMS */}
      {activeTab === "architecture" && (
        <div className="space-y-6 animate-fade-in">
          <div className="p-6 rounded-2xl bg-black/70 border border-white/10 space-y-4">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <FaLayerGroup className="text-primary" /> Architecture Component Diagram (Mermaid.js)
            </h3>
            <pre className="p-4 rounded-xl bg-white/5 text-xs text-slate-200 font-mono whitespace-pre-wrap">
{`graph TD;
    GitPushPayload --> GitHub_Monitor_Agent;
    GitHub_Monitor_Agent --> Master_Orchestrator;
    Master_Orchestrator --> Code_Analysis_Agent;
    Master_Orchestrator --> Cover_Graphic_Agent;
    Master_Orchestrator --> DocWriter_Agent;
    DocWriter_Agent --> Portfolio_UI_Sync;`}
            </pre>
          </div>

          <div className="p-6 rounded-2xl bg-black/70 border border-white/10 space-y-4">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <FaFolderTree className="text-secondary" /> Project Folder Topology
            </h3>
            <pre className="p-4 rounded-xl bg-white/5 text-xs text-slate-200 font-mono">
{`src/
├── agentic/           # EventBus & Agent Registry
├── components/        # UI Cards, Navbar & 3D Particle Canvas
├── context/           # Theme, Agent & Swarm Context Providers
├── pages/             # 18 Dedicated Operating System Pages
└── index.css          # CSS Tokens for 12 Preset Profile Themes`}
            </pre>
          </div>
        </div>
      )}

      {/* TAB 3: GUIDES */}
      {activeTab === "guides" && (
        <div className="space-y-6 animate-fade-in">
          <div className="p-6 rounded-2xl bg-black/70 border border-white/10 space-y-4">
            <h3 className="text-sm font-bold text-white">Installation & Setup Guide</h3>
            <pre className="p-4 rounded-xl bg-white/5 text-xs text-slate-200 font-mono">
{`# 1. Clone repository
git clone https://github.com/usmanghani/${repo.name}.git

# 2. Install dependencies
cd ${repo.name}
npm install

# 3. Launch dev server
npm run dev`}
            </pre>
          </div>
        </div>
      )}

      {/* TAB 4: API & DB SCHEMA */}
      {activeTab === "api_docs" && (
        <div className="space-y-6 animate-fade-in">
          <div className="p-6 rounded-2xl bg-black/70 border border-white/10 space-y-4">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <FaDatabase className="text-amber-400" /> Database Schema & API Endpoints
            </h3>
            <pre className="p-4 rounded-xl bg-white/5 text-xs text-slate-200 font-mono">
{`POST /api/v1/swarm/ingest
Header: X-Agent-Token: <SECRET>
Payload: { "repo": "${repo.name}", "event": "git.push" }

Response: 200 OK
{ "status": "INGESTED", "agentsTriggered": 10 }`}
            </pre>
          </div>
        </div>
      )}

      {/* TAB 5: REPORTS */}
      {activeTab === "reports" && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fade-in">
          <div className="p-6 rounded-2xl bg-white/5 border border-white/10 space-y-3">
            <h3 className="text-sm font-bold text-emerald-400 flex items-center gap-2">
              <FaShieldAlt /> Security Audit Report
            </h3>
            <p className="text-xs text-slate-300">OWASP Audit Score: 100/100. Zero secret leaks or vulnerable dependencies.</p>
          </div>

          <div className="p-6 rounded-2xl bg-white/5 border border-white/10 space-y-3">
            <h3 className="text-sm font-bold text-cyan-400 flex items-center gap-2">
              <FaTachometerAlt /> Performance Report
            </h3>
            <p className="text-xs text-slate-300">Lighthouse Performance: 99/100. Bundle optimization verified.</p>
          </div>
        </div>
      )}

      {/* TAB 6: ROADMAP & FAQS */}
      {activeTab === "roadmap_faqs" && (
        <div className="space-y-6 animate-fade-in">
          <div className="p-6 rounded-2xl bg-white/5 border border-white/10 space-y-3">
            <h3 className="text-sm font-bold text-primary flex items-center gap-2">
              <FaQuestionCircle /> Frequently Asked Questions
            </h3>
            <div className="space-y-2 text-xs text-slate-300">
              <div className="font-bold text-white">Q: How does automatic update work?</div>
              <div>A: Whenever a commit is pushed, GitHub Monitor Agent triggers the pipeline to update docs and resume bullets.</div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 7: DOWNLOADS */}
      {activeTab === "downloads" && (
        <div className="p-6 rounded-2xl bg-white/5 border border-white/10 text-center space-y-4 animate-fade-in">
          <FaDownload className="text-3xl text-primary mx-auto" />
          <h3 className="text-lg font-bold text-white">Download Source Package</h3>
          <button className="px-6 py-2.5 rounded-xl bg-primary text-black font-bold text-xs uppercase">
            Download .ZIP Archive
          </button>
        </div>
      )}
    </section>
  );
}

export default ProjectDetailPage;
